export const FLAVORS = [
    {
        id: 0,
        name: 'Butterscotchie',
        description: 'An oldie and a goodie. Butterscotch goodness combined with our sweet cream — an ice cream treat that is grandma and grandpa approved! ',
        image:'/images/butterscotchie.jpg',
        available: 'available',
        featured: false,
    },
    {
        id: 1,
        name: 'Ube Bae',
        description: 'Ube brings a mellow sweetness in this ice cream treat from this Filipino purple sweet potato. ',
        image:'/images/ubebae.jpg',
        available: false,
        featured: false,
    },
    {
        id: 2,
        name: 'Milky Chocolate',
        description: 'Ever dip french fries in your favorite chocolate frosty treat? Yeah, we did that too. This will definitely bring back memories of the dippage.',
        image:'/images/milkychocolate.jpg',
        available: false,
        featured: false,
    },
    {
        id: 3,
        name: 'Minty Chippy - Dairy Free',
        description: 'Even the hottest of Chicago summers don’t have a chance against the Minty Chippy. Treat yourself to the cooling after-effects of dark chocolate chunks in our cashew and coconut milk ice cream base. ',
        image:'/images/mintychippy.jpg',
        available: false,
        featured: false,
    },
    {
        id: 4,
        name: 'Cookie Crunchie',
        description: 'Cookie monsters, unite! Real talk, this was my favorite cereal growing up. The best part? The combos of crunchy and chewy pieces. Crispy rounds of chocolate chip cookies in a cereal milk base that will make you want to want to howl! ',
        image:'/images/cookiecrunchie.jpg',
        available: false,
        featured: false,
    },
    {
        id: 5,
        name: 'My Feelings',
        description: 'Ever want to eat your feelings? Well, now you can! Eat all your feelings with our newest flavor, created by Adam Bramski. Sweet Mandy B\'s fudge brownies, Reese\'s peanut butter cups, salty pretzel bits, and M&Ms fill up our chocolate ice cream base for a flavor that\'s worthy of a weekend Netflix binge of cheesy romantic comedies.',
        image:'/images/myfeelings.jpg',
        available: false,
        featured: false,
    },
    {
        id: 6,
        name: 'PB&J',
        description: 'Your fave sammich made into ice cream! Peanut butter ice cream laced with strawberry jam and we swear it tastes just like your sack lunch.',
        image:'/images/pbj.jpg',
        available: false,
        featured: false,
    },
    {
        id: 7,
        name: 'Lemon Blueberry',
        description: 'Summer time in a cup. A refreshing lemon ice cream mixed with a blueberry jam to get you in the mood for sunshine and pool time.',
        image:'/images/lemonblueberry.jpg',
        available: false,
        featured: false,
    },
    {
        id: 8,
        name: `Choco Choco - Dairy Free`,
        description: 'Cashew and coconut milk makes this chocolate, crunchy treat a creamy, luscious dream come true. Miracles do happen, people!',
        image:'/images/chocochoco.jpg',
        available: false,
        featured: false,
    },
    {
        id: 9,
        name: 'Coffee Oreo - Regular & Dairy Free',
        description: 'Why not dunk our favorite dunkable cookie in some coffee? We can, and we did! Bunches and bunches of oreos get all up in our coffee ice cream base. ',
        image:'/images/coffeeoreo.jpg',
        available: false,
        featured: false,
    },
    {
        id: 10,
        name: 'CTC',
        description: 'There ain’t no shame in this cinnamon and sugar game. This cereal staple of crunchy, sugary cinnamony squares swim in a milky ice cream base and may or may not make you want to find some Saturday morning cartoons. ',
        image:'/images/ctc.jpg',
        available: false,
        featured: false,
    },
    {
        id: 11,
        name: `Gimme S\'more`,
        description: 'Toasted ‘mallow ice cream with chunky graham crackers and a gooey chocolate drizzle. Never had these before? You’re killin’ me, Smalls!',
        image:'/images/gimmesmore.jpg',
        available: false,
        featured: false,
    },
    {
        id: 12,
        name: 'Go Manno, Go Mango, Go!',
        description: 'A tropical treat made with our sweet cream base and bunches of mangoes. And if you like piña coladas, you’ll definitely like this.',
        image:'/images/gomango.jpg',
        available: false,
        featured: false,
    },
    {
        id: 13,
        name: 'Strawberry Basil',
        description: 'A combo that first makes you go ‘hmm?’ and then makes you go ‘mmm!’. Sweet strawberry ice cream with a hint of basil, ‘cuz we fancy.',
        image:'/images/strawberrybasil.jpg',
        available: false,
        featured: false,
    },
    {
        id: 14,
        name: 'Magically Delicious',
        description: 'Rainbows, unicorns, stars, oh my! The best part about this (besides the marshmallow shapes, gorgeous color and sweet taste)? The cereal milk ice cream base. Everybody will be after this treat!',
        image:'/images/magicallydel.jpg',
        available: false,
        featured: false,
    },
    {
        id: 15,
        name: 'Ube Bae Special',
        description: 'Ube brings a mellow sweetness in this ice cream right from this Filipino purple sweet potato. To level this one up, we’re topping it with Oreo Polvoron, a traditional Filipino shortbread made of toasted flour, powdered milk, sugar, and butter.',
        image:'/images/ubebae.jpg',
        available: false,
        featured: false,
    },
]